In [8]:
import pandas as pd

# Load the csv file
csvFile = "sourceTables\鱼种场景投放与资源盘点.csv"

df = pd.read_csv(csvFile, encoding='utf-8', dtype=str)
# Step 1: Drop rows with missing '美术编号'
filtered_df = df.dropna(subset=['美术编号'])

# Step 2: Drop duplicates based on '美术编号'
distinct_df = filtered_df.drop_duplicates(subset='美术编号', keep='first')

# Step 3: Drop specified columns
columns_to_drop = ['经验（XP）', '鱼类图片1', '鱼类图片2', '鱼类图片3', '3D资源名称', '策划负责人']
cleaned_df = distinct_df.drop(columns=columns_to_drop)

# 重新整理“编号”这一列，从1开始编号
cleaned_df['编号'] = range(1, len(cleaned_df) + 1)

In [10]:
# 将“编号”这一列设置为索引
cleaned_df.set_index('编号', inplace=True)

In [6]:
# save df to a new csv file
cleaned_csv_file = "sourceTables\cleaned_fish_species.csv"
cleaned_df.to_csv(cleaned_csv_file, index=False, encoding='utf-8-sig')
print(f"Cleaned data saved to {cleaned_csv_file}")

Cleaned data saved to sourceTables\cleaned_fish_species.csv

In [11]:
cleaned_df

,名称,名称.1,美术编号,科,属,简化种类,玩法定位,价值,水层,栖息环境,钓法,鱼饵,拟饵,重量(kg),长度(cm),模型标准长度(cm),价格（金币）,备注
编号,,,,,,,,,,,,,,,,,,
1,红斑太阳鱼（幼年）,小太阳鱼（幼年）fish_redspotted_sunfish,fish_redspotted_sunfish,太阳鱼科,太阳鱼属,太阳鱼,交叉鱼种,收集,全水层,全水域洄游,浮钓,"苍蝇,蚯蚓,玉米,蜂蜜面团,种子,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-12,25,NaN,NaN
2,绿太阳鱼（幼年）,绿太阳鱼（幼年）fish_green_sunfish,fish_green_sunfish,太阳鱼科,太阳鱼属,太阳鱼,交叉鱼种,收集,顶层,"浮木,水面植物,上层结构体",浮钓,"苍蝇,蚯蚓,玉米,蜂蜜面团,种子,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-12,17,20-30,NaN
3,黑斑刺盖太阳鱼 （幼年）,黑斑刺盖太阳鱼 （幼年）fish_black_crappie,fish_black_crappie,太阳鱼科,刺盖太阳鱼属,太阳鱼,交叉鱼种,玩乐,顶层,"浮木,水面植物,上层结构体",浮钓,"蜉蝣,苍蝇,蚯蚓,玉米,蜂蜜面团,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-15,22,NaN,NaN
4,白斑刺盖太阳鱼（幼年）,白斑刺盖太阳鱼（幼年）fish_white_crappie,fish_white_crappie,日鲈科,刺盖太阳鱼属,太阳鱼,交叉鱼种,玩乐,全水层,全水域洄游,浮钓,"玉米,蜂蜜面团,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-20,26,5-10,NaN
5,蓝鳃太阳鱼（幼年）,蓝鳃太阳鱼（幼年）fish_bluegill,fish_bluegill,日鲈科,莓鲈属,太阳鱼,交叉鱼种,玩乐,全水层,全水域洄游,浮钓,"蜉蝣,苍蝇,蚯蚓",暂无路亚玩法,数值公式计算,10-15,15,无参考,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,七鳃鳗（幼年）,七鳃鳗（幼年）fish_petromyzontidae,fish_petromyzontidae,七鳃鳗目,七鳃鳗属,鳗鱼,交叉鱼种,收集,全水层,全水域洄游,浮钓,"鱼块,虾,小龙虾,螽斯",暂无路亚玩法,数值公式计算,10-13,25,NaN,NaN
59,美洲鳗鲡（幼年）,美洲鳗鲡（幼年）fish_american_eel,fish_american_eel,鳗鲡科,鳗鲡属,鳗鲡鱼,交叉鱼种,收集,底层,"底层结构体,底层植物",浮钓,"蜉蝣,苍蝇,蚯蚓,玉米,蜂蜜面团,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-80,80,NaN,NaN
60,美鳊（幼年）,美鳊（幼年）fish_common_shiner,fish_common_shiner,鲤科,美鳊属,鳊鱼,交叉鱼种,收集,全水层,全水域洄游,浮钓,"苍蝇,蚯蚓,玉米,蜂蜜面团,种子,面包,粗粮面包",暂无路亚玩法,数值公式计算,10-12,15,NaN,NaN
61,金体美鳊（传奇）,金体美鳊（传奇）fish_golden_shiner,fish_golden_shiner,鲤科,美鳊属,鳊鱼,"稀有鱼种,交叉鱼种",价值,全水层,全水域洄游,浮钓,"蜉蝣,红虫,鱼子,虾,小龙虾,螽斯",暂无路亚玩法,数值公式计算,25-30,27,NaN,NaN
62,美国红鱼（传奇）,美国红鱼（传奇）fish_red_drum,fish_red_drum,石首鱼科,拟石首鱼属,石首鱼,"稀有鱼种,交叉鱼种",高价值,全水层,全水域洄游,浮钓,"蜉蝣,苍蝇,蚯蚓,红虫,虾,小龙虾,螽斯,面包,小米诺鱼",暂无路亚玩法,数值公式计算,60-90,75,NaN,NaN